### ISSUE TITLE
Next major release

### ISSUE THREAD

**Issue by hassankhan** [rmccue/Requests#138]
Hi there, I'm a big fan of the project and have been using it for a long time now. I wanted to use it in one of my latest projects, only to find out that the main class `Requests` is a static class which doesn't exactly lend itself to DI methodologies. Also, it's not namespaced, which I assume is to keep PHP 5.2 compatibility.

I've cracked on with it and got it _mostly_ working on my [fork](https://github.com/hassankhan/Requests/tree/php5.4-and-psr-2). Right now I'm having issues getting the tests running because of problems with `requests/test-server`.

I was thinking perhaps you could release 1.7, which drops compatibility for PHP5.2 and adds namespaces, but otherwise maintains feature parity. Then we can work on 2.0, which drops compatibility for PHP5.3.

I've got a list of things that need to be done before a candidate for 1.7 is ready:
- [ ] Get tests running at same level as `master`
- [ ] Rewrite `requests/test-server` to use PHP 5.3 only
- [x] Fix specialised exception classnames

The list for 2.0 is longer, but I'm sure we can flesh it out :smile:

**Comment by rmccue** [comment]
Hi!

There's definitely some parts of Requests that could be better with interdepending on each other. One of the biggest things I want to do is turn the main `Requests` class into essentially just a wrapper around the underlying objects (kind of how Laravel's Facades work). We already have this in the form of `Requests_Session`, but the dependency is backwards right now.

> I was thinking perhaps you could release 1.7, which drops compatibility for PHP5.2 and adds namespaces, but otherwise maintains feature parity. Then we can work on 2.0, which drops compatibility for PHP5.3.

I'd love to drop compatibility for 5.2 eventually, but I don't think the timing is right just yet. The requirements here essentially sit the same as those for [WordPress](https://wordpress.org/about/requirements/), as that's a pretty good indicator of widespread server configurations. The stats there also show a [not-insignificant number](https://wordpress.org/about/stats/) of 5.2 installs. Dropping 5.3 support probably won't be possible for a while for the same reason.

*With that said*, I'd love to be able to offer Requests with namespaces for those who want it. The way I was thinking about this was basically having wrapper classes around each of Requests' internal ones, for those who want to opt-in to using it that way. This would require solving some of the DI-related issues you noted, as we'd need to be able to say "use `Requests\Response` as the response class, rather than `Requests_Response`".

Thoughts? :)

> Fix specialised exception classnames

This is something I've never really been sure about; the advantage of the current setup is that you can easily catch a simple 404 while allowing a 500 to hit an error handler higher up, but the disadvantage is that it's unnecessarily complicated to use and maintain.

I'm on the fence about changing it, since it'd necessitate a 2.0 release to break backwards compatibility.

**Comment by rmccue** [comment]
Oh, also, on the topic of PSR-2 specifically, Requests explicitly *doesn't* match the coding standard there, and I'd like to keep it with the current style.

**Comment by ozh** [comment]
One thing about 5.2: I think WP's stats are skewed by old dead WP setups. On YOURLS, a substantially newer project, PHP 5.2 is at **5.4%** and constantly going down.

**Comment by hassankhan** [comment]
Ah right, I actually started going through the `docs` folder and realised that the whole point of Requests was to work on PHP5.2+, that's why I closed the issue.

I personally think we should only support PHP5.4+, because the language improvements help clear up the code immensely IMO. That said, I've almost got my branch to a point where it fully works on PHP5.3 (I actually need some help if anyone could spare some time :smile:), and I'd love some more feedback.

Thanks!

**Comment by hassankhan** [comment]
For further reading: 

- http://seld.be/notes/my-view-of-php-version-adoption
- http://blog.ircmaxell.com/2014/12/php-install-statistics.html
- http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html

My point being... PHP5.2 is old and insecure, and IMO we should encourage people to upgrade to newer, more secure versions of PHP

**Comment by hassankhan** [comment]
I had a think about creating wrapper classes, and that could easily be done I'm guessing:

```php
abstract class AbstractWrapper
{

    protected $rootClass;

    abstract public function getRootClass();

    public function __construct()
    {
        $rootClass = new $this->getRootClass();
    }

    public function __call($method, $arguments)
    {
        return call_user_func_array(array( $this->rootClass, $method ), $arguments);
    }

}

class MyWrapper extends AbstractWrapper
{

    public function getRootClass()
    {
        return 'RootClass';
    }

}
```

Just make a bunch of those, all namespaced and everything, dump those in the `src` folder and autoload that as PSR-4. Not an ideal solution though (could cause problems?)

**Comment by hassankhan** [comment]
[Another nail in the coffin](https://make.wordpress.org/meta/2015/03/01/major-update-to-our-version-stats-for-php-mysql-and-wordpress/) for PHP 5.2?

**Comment by rmccue** [comment]
> Another nail in the coffin for PHP 5.2?

I've had access to the updated stats for a while now. :) While they're lower than the previous version, as noted in that post:

> So, I wish to note that this does *not* change our calculations for keeping PHP 5.2 as the minimum for WordPress core — we had these numbers available to us when preparing our 2015 plans.

**Comment by rmccue** [comment]
Also:

> PHP5.2 is old and insecure, and IMO we should encourage people to upgrade to newer, more secure versions of PHP

I personally disagree with Anthony on that one, as does the WP team. We've spoken about it before. :)

**Comment by TysonAndre** [comment]
Okay, wordpress still supports 5.2, 2 years later.

Is there any reason making it impossible to release and maintain multiple major versions, e.g.

- 1.x : For crash fixes and security fixes, keeping API mostly the same (Link users to README for specific branch)
- 2.x for PHP 5.3+ , not supporting lower versions , can use namespaces, https://secure.php.net/manual/en/language.oop5.late-static-bindings.php (e.g. to subclass `Request`, to be guaranteed class_alias exists)
- 3.x for PHP 7.0+ , not supporting 5.x, and allowing developers to use return types/scalar type hints/null coalescing/short arrays (Much less important than namespaces.)

Other motivations for this:

- Easier to contribute, it's harder to create PRs if it must support versions that are hard to install (5.2), and require methods that developers won't remember were added in 5.3, not 5.2.
- Can use newer composer libraries if desired

**Comment by rmccue** [comment]
PHP 5.2 usage for WordPress is [down to 4.8%](https://wordpress.org/about/stats/), and I suspect it may drop compatibility soon. (We have the WordPress Contributor Summit in Paris in a few days, and I'll bring it up there.)

I'd rather not break API compatibility generally speaking (minor breaks are sometimes OK), but if we can move to 5.3+, we can handle that all via `class_alias`; in that scenario, we can use namespaces for everything internally, and add a compatibility layer separately.

Unfortunately, PHP 7.0-only support is probably pretty far off, since (per [this comment](https://github.com/wp-cli/wp-cli/issues/3909#issuecomment-300504615)):
> RHEL/CentOS 6 ends support in Nov 2020 and ships PHP 5.3.3, whereas RHEL/CentOS 7 ends support in June 2024 and ships PHP 5.4.16

Those versions are going to be in use for a long time.

As for contributing, I mostly just work on my local (PHP 7.1) setup, and let Travis handle compatibility testing.
