### ISSUE TITLE
Problem with GET parameters 

### ISSUE THREAD

**Issue by rootuser** [rmccue/Requests#142]
I am confused; while the requests lib is working great basically, there seems to be a severe issue with GET requests; or maybe I get the concept wrong, for it is not covered in the documentation.

Basically, I wish to execute a GET request with parameters, so it would look like
http://some.uri.tld/some-service?param1=abcde&param2=12345

The 'real' work of requests is done in the Requests_Transport_cURL class; in the function 'setup_handle' the cURL handle is prepared, and there are a few lines regarding the request data:

if (in_array($options['type'], array(Requests::HEAD, Requests::GET, Requests::DELETE)) & !empty($data)) {
			$url = self::format_get($url, $data);
		}
		elseif (!empty($data) && !is_string($data)) {
			$data = http_build_query($data, null, '&');
		}

Thing is: though there obviously is a formatter function to convert the $data parameter array to the GET URI format, the $data variable will always be empty for GET requests, because the request::get function has no $data parameter and passes NULL for $data to the requests::request function.

Can you confirm this being an issue, or am I geting something utterly wrong?

Thank you, 
regards, Tom

**Comment by ulukaiulukai** [comment]
I also just stumbled upon this. Setting the query string of GET requests via the data parameter seems to be broken.

    $data = ['test' => '1'];

    $url = 'http://httpbin.org/get';
    Requests::get($url, [], $data); // returns {"args": {}}

Workaround:

    $url = 'http://httpbin.org/get?' . http_build_query($data);
    Requests::get($url); // returns {"args": {"test": "1"}}

This isn't exactly what the data parameter is supposed to do (because it should also merge the data with an existing query string), but it's close enough.

I wonder why this isn't covered by the tests?

**Comment by rmccue** [comment]
This is an intentional part of the API design; in a typical use case, you won't necessarily need data sent along with a request. Building the URL for you is just a convenience.

`Requests::get` is a helper function designed to make GET requests lightweight in the code, which is why there's no `$data` parameter there. If you need to send data, use `Requests::request` instead:

```
$headers = [];
$data = ['test' => '1'];
$options = [];
$response = Requests::request( 'http://httpbin.org/get', $headers, $data, Requests::GET, $options );
// GET is the default for type, and $options can be blank, so this can be shortened:
$response = Requests::request( 'http://httpbin.org/get', $headers, $data );
```

@ulukaiulukai Your code there is actually setting the `test` option to `'1'`, which doesn't do anything. :) Use `Requests::request` as above instead.

**Comment by nikans** [comment]
That's counterintuitive. Also, couldn't find a spec for $options
