### ISSUE TITLE
The PSR-0 `Requests_...` class names in the Request library are deprecated.

### ISSUE THREAD

**Issue by JohnLBergqvist** [rmccue/Requests#708]
### Given the following code sample

I have installed requests 2.0.2 via composer, using
```php
composer require rmccue/requests
```

And loaded via
```
require_once dirname(__FILE__) . '/vendor/autoload.php';
```

### I'd expect the following behaviour
No error message such as the one shown below

### Instead this happened
Requests appears to work, however I get the following error every time:
```
Deprecated: The PSR-0 `Requests_...` class names in the Request library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience. in vendor/rmccue/requests/library/Requests.php on line 24
```

## Your environment

| Environment                                                  | Answer
| ------------------------------------------------------------ | -------
| Operating system and version (e.g. Ubuntu 20.04, Windows 10) | Ubuntu 20.04
| PHP version                                                  | 7.4
| Requests version                                             | 2.0.2
| Autoloader used                                              | Composer autoload

## Tested against `develop` branch?
- [ ] I have verified the issue still exists in the `develop` branch of Requests.

**Comment by jrfnl** [comment]
@JohnLBergqvist Version 2.0.0 is a major release containing breaking changes. Please see the [release notes](https://github.com/WordPress/Requests/releases/tag/v2.0.0) and the [Upgrade guide](https://requests.ryanmccue.info/docs/upgrading.html).

Closing this now as the behaviour you describe is intentional and the notice can be silenced via a constant.

Sorry to say it, but this is a case of "I couldn't be bothered to read the docs".

**Comment by JohnLBergqvist** [comment]
@jrfnl Might I recommend this be added to your quick-start guide re. using the autoloader on the website? Given that this was a fresh installation, I did not read the changelog.

**Comment by jrfnl** [comment]
@JohnLBergqvist Not sure what happened as I don't see the message here, but I did receive email notification of a reply saying:

> @jrfnl Might I recommend this be added to your quick-start guide re. using the autoloader on the website? Given that this was a fresh installation, I did not read the changelog.

If that's the case, I'd love to see the code which causes the deprecation notice and a link to the quick start guide you are referring to.

If you follow any of the documentation on the website or the Readme, you shouldn't be able to get the notification. We tried to make sure all docs were updated for the changes.

Did we miss updating a particular page ?

Or could it be you used `Requests::...` in your code instead of the fully qualified name and/or without an import `use` statement ?

**Comment by adeleyeayodeji** [comment]
I resolved this issue by changing the previous class name `Requests` to the new added namespace `WpOrg\Requests\Requests` 

Sample with new namespace
```php
  //get countries
        $response  = \WpOrg\Requests\Requests::get(self::$enpoint . 'countries', [
            'Authorization' => 'Bearer ' . self::$skkey,
  ]);

```

**Comment by ezicrea** [comment]
> Resolví este problema cambiando el nombre de la clase anterior `Requests`al nuevo espacio de nombres agregado`WpOrg\Requests\Requests`
> 
> Muestra con nuevo espacio de nombres
> 
> ```
>   //get countries
>         $response  = \WpOrg\Requests\Requests::get(self::$enpoint . 'countries', [
>             'Authorization' => 'Bearer ' . self::$skkey,
>   ]);
> ```

Hola puedes precisar la ruta del archivo, donde realizaste el cambio?
Gracias de antemano.

**Comment by adeleyeayodeji** [comment]
This is my codebase, you can edit the namespace in your codebase
